### ISSUE TITLE
A query about  MomentsEstimator

### ISSUE THREAD

**Issue by saadm2** [proteus-h2020/proteus-solma#19]
Hi,

As far as I understood from the code below is that the aggregation of the moments coming from different machines are done at the end, after all the data samples have been processed. I wonder if this code is the final version. I mean, in real real world scenarios the data is unbounded and the aggregation should be done after each iteration. If you could provide some clarifications, that will help me implement other algorithms like the Online PCA.

Many Thanks
Saad

val intermediate = statefulStream.mapWithState((in, state: Option[Moments]) => {
          val (event, pid) = in
          val slice = event.slice
          val x = event.data.asBreeze
          val metrics = state match {
            case Some(curr) => {
              curr.process(x, slice)
            }
            case None => {
              new Moments(x, slice, featuresCount)
            }
          }
          ((pid, metrics), Some(metrics))
        })

        if (resultingParameters(AggregateMoments)) {
          intermediate.fold(new mutable.HashMap[Int, Moments]())((acc: mutable.HashMap[Int, Moments], in) => {
            val (pid, moments) = in
            acc(pid) = moments
            acc.remove(-1)
            val it = acc.values.iterator
            val ret = it.next.clone()
            while (it.hasNext) {
              ret.merge(it.next)
            }
            acc(-1) = ret
            acc
          }
        ).map(data => (0, data(-1)))
        } else {
          intermediate
}

**Comment by VenturaDelMonte** [comment]
Hi, yes, that's partially true. The aggregation is done as soon as one of the parallel instances produces a new value, hence at the end of each "iteration" in a sense, albeit this is an optional step. As a matter of facts, we are not using such aggregation at all in the proteus-job [1], because we are calculating mean and variance per (coil, sensor), therefore, there is no need to aggregate those values among different pairs. I hope this helps you in better understanding the implementation of the algorithm.

[1] https://github.com/proteus-h2020/proteus-job/blob/development/src/main/scala/eu/proteus/job/operations/moments/MomentsOperation.scala#L47

**Comment by saadm2** [comment]
Many Thanks for the explanation, I think that i have to study [1] and the pipelines codes thoroughly to understand better the concept.
My questions might sound naive, but just to check my initial understanding, in SOLMA, is it 
 possible to send, receive or share knowledge among different parallel instances as data streams ?

**Comment by jeyhunkarimov** [comment]
@saadm2 it depends on your use-case. If you can partition your "knowledge" then you can efficiently share it between parallel instances. If your "knowledge" is small like metadata, you can also use broadcasting the data. Otherwise, you can use PEACH, which is developed by Novelti as part of Proteus. Although it is not integrated with Proteus engine yet, I think it will be soon.

**Comment by VenturaDelMonte** [comment]
@saadm2 regarding your not-naive-at-all question, we will use a parameter server to share partial models updates. This will happen somewhen soon. We will also need such feature for the LASSO+AA implementation. HTH.

**Comment by saadm2** [comment]
Many Thanks  @VenturaDelMonte and @jeyhunkarimov
