### ISSUE TITLE
Moments 

### ISSUE THREAD

**Issue by waqasjamyl** [proteus-h2020/proteus-solma#8]
`def this(x: BreezeVector[Double]) = this(1L, x.copy, BreezeVector.zeros[Double](x.size))`

Does the above code imply that you are assuming the size of the incoming data?

**Comment by jeyhunkarimov** [comment]
Hi, if you mean by "size of the incoming data" the size of vector, then yes we assume that we know.

**Comment by waqasjamyl** [comment]
I'm still catching up on Flink, but hope to I can find a way to avoid it. Thank you!

**Comment by waqasjamyl** [comment]
I want to implement the following code in Flink ML pipeline. My problems are: 

1. I don't have parameters in class covar, because I don't want to specify the length of the data.
2. I have a tuple of (x,y) in my add function.
3. I don't know much operations in Flink ML.

Due to my problems I can't use the template of Moments in SOLMA, I am still reading the following [link](https://ci.apache.org/projects/flink/flink-docs-release-1.2/dev/libs/ml/pipelines.html). If someone can provide some hints or guide me through ?

```
import eu.proteus.annotations.Proteus
import eu.proteus.solma.pipeline.{StreamFitOperation, StreamTransformer}


@Proteus
class Covariance extends StreamTransformer[Covariance]{


  /**
    * Created by waqas on 02/05/17.
    *
    */
  object Covariance {

    class covar {

      var xAvg = 0.0
      var yAvg = 0.0
      var Ck = 0.0
      var MkX = 0.0
      var MkY = 0.0
      var count = 0L

      def add(x: Double, y: Double): this.type = {
        val deltaX = x - xAvg
        val deltaY = y - yAvg
        count += 1
        xAvg += deltaX / count
        yAvg += deltaY / count
        Ck += deltaX * (y - yAvg)
        MkX += deltaX * (x - xAvg)
        MkY += deltaY * (y - yAvg)
        this
      }

      def merge(other: covar): this.type = {
        if (other.count > 0) {
          val totalCount = count + other.count
          val deltaX = xAvg - other.xAvg
          val deltaY = yAvg - other.yAvg
          Ck += other.Ck + deltaX * deltaY * count / totalCount * other.count
          xAvg = (xAvg * count + other.xAvg * other.count) / totalCount
          yAvg = (yAvg * count + other.yAvg * other.count) / totalCount
          MkX += other.MkX + deltaX * deltaX * count / totalCount * other.count
          MkY += other.MkY + deltaY * deltaY * count / totalCount * other.count
          count = totalCount
        }
        this
      }

      def cov: Double = Ck / (count - 1)

      override def toString: String = {
        "[covar=" + Ck.toString + "]"
      }
    }

    def apply(): covar = {
      new covar()
    }
  }
}
```
```

**Comment by VenturaDelMonte** [comment]
Hi Waqas, I try to structure my answer as a list:

1. if with size of the data, you mean the number of features that each model supports, then yes.
2. Why do you say that specifying the number of features is desirable?  
3. after last meeting, we realised that features for the same object come at different speed (asynchronously), therefore, I introduced #11 , which enables to deal with such a scenario. 
4. What's the usage of covariance here? Do you want to calculate the covariance between two features (or subset of features)?

**Comment by waqasjamyl** [comment]
**Covariance**

I want to calculate covariance between two data points. For example we have a matrix of n rows and 2 columns. At each step a row is selected and the two columns (the 2 data points of each column) are compared.

**Moments**

Consider If we have a matrix of n rows and m columns. If you specify the size of m columns it should be fine, but if it is n rows, then it is a problem.

**Comment by VenturaDelMonte** [comment]
Just to clarify, we do not assume the amount of data points because we are doing online learning and we are in a streaming environment, thus we cannot know how many samples (or as you say how many rows of the matrix) the system ingests. What we can know in advance is the number of features (variables / number of columns) because this is something inherent the underlying data (e.g., temperature, pressure, flatness). 
That being said, I think each algorithm should be aware of the number of features as we are writing general algorithms that may be configured on different use cases (e.g., coils flatness prediction). 
In the current code (the one you are referring to), we assumed to get a sample (row) at a time (with all the not-nulled features/variables/columns). Therefore, each parallel moments processor calculates the online mean and variance for a subset of the samples (rows) on all their features (columns). However, this is not a realistic assumption, because as we found out, subsets of features (columns) for a given sample (row) come at different speed. Thus, I proposed in #11 a way to handle such new scenario.

Regarding the **covariance**, before I can give you an answer, I would ask you to check #11 please, then we may further discuss how to implement covariance.

**Comment by waqasjamyl** [comment]
I agree with you, so my understanding of the code was incorrect, thank you for the clarification. In future I will try to ask more constructive question. Regarding the issue does assigning some sort of an id to each feature resolve the problem?Is it even possible? 

I mean let's say we have n feature (x_1,...,x_n) where x is a vector. So if you can assign n unique tags to them, then you can know each sample belongs which feature.

Please ignore if my suggestion does not seem plausible.

**Comment by VenturaDelMonte** [comment]
Anytime, but actually your question was very good because we finally come up with a unified view of our processing model :)
